### ISSUE TITLE
Create network layer

### ISSUE THREAD

**Issue by julyakmita** [ios-course/ironfoudation-team-project#59]
## The scope of the current task:
- #120 
- #121
- https://github.com/ios-course/simple-network-service/issues/5
- https://github.com/ios-course/simple-network-service/issues/3
- https://github.com/ios-course/simple-network-service/issues/6

## Description
The goal of this task is to implement a generic networking layer. 
This class should not have any data that is related to a specific View or ViewModel.

**High-level idea of implementation**: 
Code to get the [main idea](https://gist.github.com/NadzeyaShpakouskaya/b6a838d8c49f480cdb20a0122cdf30fb) of how the network layer can be implemented

**Comment by iBYarchitect** [comment]
Network Layer: The network layer is responsible for making network requests, handling responses, and managing the communication with remote servers or APIs. It encapsulates the networking code and provides an interface for the view models to interact with the network.

- API client: A class or service that encapsulates the logic for making HTTP requests to the remote server or API. It handles tasks like constructing the request, setting headers, encoding parameters, and handling authentication.

- Response handling: This part of the network layer processes the responses received from the server. It may include parsing the response data (e.g., JSON), handling errors, and transforming the data into usable formats for the view models.

- Asynchronous operations: Since network requests are typically asynchronous, the network layer might use mechanisms like completion handlers, callbacks, or promises to handle the asynchronous nature of network operations and provide responses to the calling components.

**Comment by kirpichonok** [comment]
Closed with PR [#1](https://github.com/ios-course/simple-network-service/pull/14)
